---
cloudformation_retries: 0
env_type:                     ansible-tower
email:                        babylon@example.com
own_repo_path:                <Need to be Populated>
cloud_provider:               ec2
aws_region:                   <Need to be Populated>
guid:                         <Need to be Populated>

agnosticv_meta:
  idle_after_deploy: 1


### Env Related Variables

software_to_deploy: tower
tower_instance_count: 1
support_instance_count: 1
worker_instance_count: 0