---
## This is a costing tag, make sure the value passed makes sense
purpose: development
lets_encrypt_production: false
run_ocp_diagnostics: false
cloudformation_retries: 0

bastion_instance_type: "{{ 't2.large' if node_instance_count|int <= 10 else 't2.xlarge' }}"
master_instance_type: m4.2xlarge
infranode_instance_type: m4.4xlarge
node_instance_type: m4.4xlarge
support_instance_type: t2.medium

agnosticv_meta:
  ## This may need to be modified, depending on what is expected of the CI
  ## As opposed to OC4, we have no challenges related to idle times for OCP3
  idle_after_deploy: 2
  idle_after_start: 8
