---
cloudformation_retries: 0
clientvm_instance_type: t2.medium
env_type:                     ocp-clientvm
email:                        babylon@example.com
own_repo_path:                <Need to be Populated>
cloud_provider:               ec2
aws_region:                   <Need to be Populated>
guid:                         <Need to be Populated>

agnosticv_meta:
  idle_after_deploy: 1
