---
purpose: development  ## This is a cost tag, please make sure it's correct.
osrelease: 4.1.4
cloudformation_retries: 0

bastion_instance_type: "{{ 't2.large' if node_instance_count|int <= 10 else 't2.xlarge' }}"
master_instance_type: m4.xlarge
worker_instance_type: m4.4xlarge
_infra_instance_type: m4.4xlarge
_infra_node_replicas: 1

## Here you can add or remove as many workloads as you want to be executed after cluster deploy
## When running env_type ocp4-workshop this is useful to modify the default workloads executed
## You can also add here infra_workloads or student_workloads
## The more workloads you add, you will have to make sure the variables to make them work properly are in place
## This will require you to go to back to the AgnosticD repo and look at their defaults

default_workloads:
  - ocp4-workload-enable-lets-encrypt-certificates
  - ocp-workload-terminal

agnosticv_meta:
  ## Depending on what is to be done with this CI, idle times should be modified for costing purposes.
  ## For OCP4, at the time of writing, a value of at least 26 should be allocated to the idle_after_deploy variable.
  idle_after_deploy: 26
  idle_after_start: 12
